/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
